``
`\`
`\a`
`\b`
`\n`
`\v`
`\t`
`<CR>`
`\\`
`\"'`
`""`
`"""""""""`
`"       "`
`   aaa bbb ccc `
`{`
`}`
`{}`
`# blah blah blah`
`\u4F60`
`\U0001F600`
`C:\path`
`"a\nb"`
`"a\n#bbb"`
`\\server\share`
`\d+\.\d+`
`\a\b\f\n\r\t\v\\\'`
`$`
`{$HOME}`